### ISSUE TITLE
Bucket Mouse tracking 

### ISSUE THREAD

**Issue by Latios96** [Latios96/crayg#136]
Bucket mouse tracking (inspired by V-Ray)

- [x] track mouse position in image
- [x] store buckets in a data structure that allows for nearest neighbor search in image space
- [x] provide an abstraction over "getting the next bucket"
- [x] make it possible to switch that during runtime
- [x] mouse tracking should only be possible in the UI, provide a button in the UI

Get relative coordinates of cursor in image:

```c++
auto point = this->widget()->mapFromGlobal(QCursor::pos());
    auto pointf = QPointF(static_cast<float>(point.x()) / this->widget()->width(),
                          static_cast<float>(point.y()) / this->widget()->height());
```

Bucket Queue

```c++
struct BucketQueue{
    enum Mode{
        FOLLOW_SEQUENCE,FOLLOW_MOUSE;
    };
    std::optional<ImageBucket> nextBucket(){
        // follow mouse
        // get mouse position
        // find nearest bucket
        // remove bucket from data structure
        // mark bucket for removal
        
        // follow sequence:
        // get and increment the index counter
        // return the element
    }
    std::function<Vector2i()> getMousePosition();
};
```

Bucket Queue: sucht den nächsten Bucket anhand des Modus heraus
CellGrid: effiziente queries des nächsten Bucket mithilfe von spatial subdivision
