### ISSUE TITLE
Implement lens models

### ISSUE THREAD

**Issue by Latios96** [Latios96/crayg#80]
## Tasks
- [x] read / write camera type and lens file path attributes to USD
- [x] add CameraModel Factory
- [x] implement Thin Lens Model
- [x] parse Lens data
- [x] instead of storing a path to a LensFile on the camera, rather store a Pointer to an optional lens model. This way, reading the actual data can be done by Scene IO
- [x] write lens data embedded 
- [x] implement [Realistic Camera](https://www.pbr-book.org/3ed-2018/Camera_Models/Realistic_Cameras)
- [x] Naheinstellgrenze berechnen
- [ ] Bug: https://cato.frmbffr.com/projects/4/runs/953/tests?selectedTest=20829 schwarzer Rand Links? #121 ?
- [x] don't modify lens to set focus, set an offset on the lens instead
- [x] don't modify aperture, instead, store current radius on lens
- [x] write used lens name, aperture, focus distance, focal length, effective focal length and other interesting camera parameters to Image Metadata

### USD Attributes
`craygCameraType`: Enum with values `Pinehole`, `Thin_Lens`, `Realistic`
`craygLensFilePath`: String

Maya:
To specify and export these attributes to USD,  the `USD_UserExportedAttributesJson` attribute has to be created. In order to get the wanted name in USD, the format of the JSON needs to be the following

`{"craygCameraType":{"usdAttrName":"craygCameraType"}}`

Seems like for float attrs there should also be `"translateMayaDoubleToUsdSinglePrecision": true` present

## Test data
[Open Chess Set](https://github.com/usd-wg/assets/tree/main/full_assets/OpenChessSet)
[Storm Trooper](https://www.blendswap.com/blend/13953)

#### Cooke Speed Panchro
Reference Data from [ShareGrid Lens Test](https://www.sharegrid.com/learn/lens-sets/cooke-speed-panchro)
Patent GB157040A (found [here](https://www.lentil.xyz/docs/available_lens_models.html#cooke-speed-panchro))
